### ISSUE TITLE
Error establishing webhook configuration via Eventbrite API. Eventbrite said: 403: NOT_AUTHORIZED: This user is not able to use legacy user endpoints, please use the organization equivalent.

### ISSUE THREAD

**Issue by harshal6** [twomice/com.joineryhq.eventbrite#22]
on the settings page /civicrm/admin/eventbrite/settings?reset=1 , I get an error that 
Notice: Undefined index: webhooks in CRM_Eventbrite_Form_Settings->_confirmWebhookOnFormLoad() (line 296 of modules/civicrm_ext/com.joineryhq.eventbrite/CRM/Eventbrite/Form/Settings.php).
and it says
Error establishing webhook configuration via Eventbrite API. Eventbrite said: 403: NOT_AUTHORIZED: This user is not able to use legacy user endpoints, please use the organization equivalent.
I have added Personal Oauth token and created an organization on eventbrite.

**Comment by harshal6** [comment]
As per the changelog in the EventBrite API 
https://www.eventbrite.com/platform/docs/changelog

GET /v3/webhooks/ is legacy and needs to be changed to 

GET /v3/webhooks/ | GET /v3/organizations/{organization_id}/webhooks/

**Comment by twomice** [comment]
Hi @harshal6 

I'm seeing some indications that the api used for establishing webhooks (and some other EB apis) are unsupported after June 1, 2020:

https://jsapi.apiary.io/apis/eventbriteapiv3public/reference/webhooks/create/create-webhooks-deprecated.html (references the OP's error message)
https://www.eventbrite.com/platform/docs/changelog documents various specific deprecations.

See also #21

I believe this means we have a need for a patch in this extension that will support compatibility with this change in the EventBrite api. If you are able to provide a PR (or sponsor development of such a patch), that would be a welcome contribution.

**Comment by harshal6** [comment]
Yes I would be happy to contribute working towards it.

**Comment by twomice** [comment]
Thanks @harshal6 that's great to hear. If you have any questions please let me know.

**Comment by harshal6** [comment]
Hi @twomice I have fixed the API webhook error on the form settings, now I am trying to understand how the eventbrite is synced with CiviCRM 
Kindly review my [changes](https://github.com/twomice/com.joineryhq.eventbrite/pull/23) and provide inputs and fixes wherever needed.
Thanks

**Comment by twomice** [comment]
I'm including this issue in a batch closing of older tickets. It may be that this this issue has been resolved, or we may need more information. Please feel free to re-open.

Also note: FYI, I've updated the README file with a note on project status. Because we don't use EB here, it's hard for me to keep this up to date, though I'm hopeful some EB user organization will be interested in sponsoring the work to get it working agian.

## NOTICE of project status
### This project is known to have significant issues with the current EventBrite API.
Although it worked well when first released, EB has made changes to their API, and this extension is very likely not to work completely, or perhaps in any usable way.

If you're a current EventBrite user who'd like to help sponsor the work needed get this working again, please contact us directly via https://joineryhq.com/ to discuss your needs.
